### ISSUE TITLE
Numbers do not reset

### ISSUE THREAD

**Issue by Qadister** [NickJordan289/NoPixel_Lockpick_Bot#5]
I wrote earlier but I do not know if you saw, the point is that the program enters the number that appeared earlier, i.e. if it is 1 and then 2, it enters 1 instead of the current 2

**Comment by NickJordan289** [comment]
Hi, sorry I did miss it earlier and have tested for myself and can see what you are talking about. 

I'll update when I have solved the issue.

**Comment by NickJordan289** [comment]
Please see latest commit - should solve your issues

**Comment by Qadister** [comment]
thanks so much
