### ISSUE TITLE
Similar type of minigame but different colors.

### ISSUE THREAD

**Issue by PastafarianKvoux** [NickJordan289/NoPixel_Lockpick_Bot#7]
How would I go about modifying this to another version which looks the same, but has different colors? I edited this:

    blue_bar_lower = np.array([36, 46, 66], dtype="uint8") # Min HSV threshold for blue target bar
    blue_bar_upper = np.array([28, 139, 77], dtype="uint8") # Max HSV threshold for blue target bar
    
    And I also edited the zone. The numbers look almost/very close the same as the png's provided.

![Untitled](https://user-images.githubusercontent.com/39137480/202689911-25f90685-5402-40c8-84fd-d1cb9e8498a8.png)

**Comment by NickJordan289** [comment]
> How would I go about modifying this to another version which looks the same, but has different colors? I edited this:
> 
> 
> 
>     blue_bar_lower = np.array([36, 46, 66], dtype="uint8") # Min HSV threshold for blue target bar
> 
>     blue_bar_upper = np.array([28, 139, 77], dtype="uint8") # Max HSV threshold for blue target bar
> 
>     
> 
>     And I also edited the zone. The numbers look almost/very close the same as the png's provided.
> 
> 
> 
> ![Untitled](https://user-images.githubusercontent.com/39137480/202689911-25f90685-5402-40c8-84fd-d1cb9e8498a8.png)
> 
> 
You'll need to update the number templates with the ones from your game.
You can use something like this colour range calculator to find the upper and lower range of the zone you need to hit the number.
https://github.com/srane96/HSV-Color-Range-Calculator

**Comment by PastafarianKvoux** [comment]
Thanks for the quick respone, il try my best :)
