### ISSUE TITLE
question

### ISSUE THREAD

**Issue by piterek561** [NickJordan289/NoPixel_Lockpick_Bot#9]
How to edit this to game with other colors?

**Comment by NickJordan289** [comment]
You will need to edit the upper and lower colour ranges to match your game.
![image](https://user-images.githubusercontent.com/35259816/211236746-206e41b2-e1dd-4082-b1a2-42026d7f80c0.png)

You can adapt a tool like this to give you the values.
https://github.com/srane96/HSV-Color-Range-Calculator
